global cargador;
global A1;
global arch1dato;
global arch2dato;
global arch3dato;


    
    global arquivo1  ; 
    global arquivo2;
    global arquivo2;
    cargador = figure('Color',[1 1 1], ...
        'MenuBar','none', ...
        'Name','seleccione archivos', ...
        'NumberTitle','off', ...
        'PaperUnits','points', ...
        'Position',[100 150 590 420], ...
        'Tag','figcarga', ...
        'ToolBar','none');
    
            axes('Position',[0 0 1 1]);
            imagen=imread('Tela4.bmp');
            image(imagen);
            axis off;
            
            

            
            
            
    
         browse1 =       uicontrol('parent',cargador, ...
        'Units','points', ...
        'BackgroundColor',[0.9 0.9 0.9], ...
        'Callback','[arch1dato,padarch1dato] = uigetfile({''*.dat'',''arquivos de dados (*.dat)'';},''Carregue o arquivo'');set(nomarq1,''string'',arch1dato);set(nomarq2,''Visible'',''on'');set(browse2,''Visible'',''on'');arquivo1 = load (arch1dato);', ...
        'ListboxTop',0, ...
        'Position',[345 135 90 20], ...
        'String','Browse', ...
        'Tag','browse1');
    
        browse2 =        uicontrol('parent',cargador, ...
        'Units','points', ...
        'BackgroundColor',[0.9 0.9 0.9], ...
        'Callback','[arch2dato,padarch2dato] = uigetfile({''*.dat'',''arquivos de dados (*.dat)'';},''Carregue o arquivo'');set(nomarq2,''string'',arch2dato);set(nomarq3,''Visible'',''on'');set(browse3,''Visible'',''on'');arquivo2 = load (arch2dato);', ...
        'ListboxTop',0, ...
        'Position',[345 105 90 20], ...
        'String','Browse', ...
        'Tag','browse2');
    
         browse3 =       uicontrol('parent',cargador, ...
        'Units','points', ...
        'BackgroundColor',[0.9 0.9 0.9], ...
        'Callback','[arch3dato,padarch3dato] = uigetfile({''*.dat'',''arquivos de dados (*.dat)'';},''Carregue o arquivo'');set(nomarq3,''string'',arch3dato);set(nomarq4,''Visible'',''on'');set(browse4,''Visible'',''on'');arquivo3 = load (arch3dato);', ...
        'ListboxTop',0, ...
        'Position',[345 75 90 20], ...
        'String','Browse', ...
        'Tag','browse3');
    
         browse4 =       uicontrol('parent',cargador, ...
        'Units','points', ...
        'BackgroundColor',[0.9 0.9 0.9], ...
        'Callback','[arch4dato,padarch4dato] = uigetfile({''*.dat'',''arquivos de dados (*.dat)'';},''Carregue o arquivo'');set(nomarq4,''string'',arch4dato);set(nomarq4,''Visible'',''on'');set(browse4,''Visible'',''on'');arquivo4 = load (arch4dato);', ...
        'ListboxTop',0, ...
        'Position',[345 45 90 20], ...
        'String','Browse', ...
        'Tag','browse3');

    
    
    
    
    
    
    
         nomarq1 =   uicontrol('Parent',cargador,...
        'Style','text', ...
        'Units','points', ...
        'HorizontalAlignment','left', ...
        'BackgroundColor',[0.5 0.6 0.8], ...
        'ListboxTop',1, ...
        'Position',[240 135 100 18], ...
        'String',arch1dato, ...
        'Visible','on',...
        'Tag','nomarq1');
    
    
         nomarq2 =   uicontrol('Parent',cargador,...
        'Style','text', ...
        'Units','points', ...
        'HorizontalAlignment','left', ...
        'BackgroundColor',[0.5 0.6 0.8], ...
        'ListboxTop',1, ...
        'Position',[240 105 100 18], ...
        'String',arch2dato, ...
        'Visible','on',...
        'Tag','nomarq2');
    
         nomarq3 =   uicontrol('Parent',cargador,...
        'Style','text', ...
        'Units','points', ...
        'HorizontalAlignment','left', ...
        'BackgroundColor',[0.5 0.6 0.8], ...
        'ListboxTop',1, ...
        'Position',[240 75 100 18], ...
        'String',arch3dato, ...
        'Visible','on',...
        'Tag','nomarq3');
    
         nomarq4 =   uicontrol('Parent',cargador,...
        'Style','text', ...
        'Units','points', ...
        'HorizontalAlignment','left', ...
        'BackgroundColor',[0.5 0.6 0.8], ...
        'ListboxTop',1, ...
        'Position',[240 45 100 18], ...
        'String',arch3dato, ...
        'Visible','on',...
        'Tag','nomarq3');    
    
    
    
    
A = findobj('tag','browse2');
set(A,'Visible','off');
A = findobj('tag','browse3');
set(A,'Visible','off');
A = findobj('tag','browse4');
set(A,'Visible','off');
A = findobj('tag','browse5');
set(A,'Visible','off');
A = findobj('tag','nomarq2');
set(A,'Visible','off');
A = findobj('tag','nomarq3');
set(A,'Visible','off');
A = findobj('tag','nomarq4');
set(A,'Visible','off');
A = findobj('tag','nomarq5');
set(A,'Visible','off');
    

    
    
    
    %-----------aceptar-------------
    
            uicontrol('parent',cargador, ...
        'Units','points', ...
        'BackgroundColor',[0.9 0.9 0.9], ...
        'Callback', 'close(cargador);tutorialinicio2' , ...
        'ListboxTop',0, ...
        'Position',[25 35 90 20], ...
        'String','Aceptar', ...
        'Tag','acept1');
   

            
            
            
            
            

    %set(handles.nomarq1,'string',arch1dato);

    
 


