% Filtrar.m
% SONIDO 1.0 ®
% Desarrollado Por: Juan Guillermo Valencia Delgado
%                   Sergio Andres Hurtado Ruiz
%                   Felipe Restrepo Naranjo
%                   Jeferson Barrera caceres
% Fecha: Abril de 2009        
% Contenido:    Menú de filtrado 
%               Se escoge que tipo de filtro utilizar, el orden, las 
%               frecuencias de corte, y el archivo a filtrar.


function Filtrar

    [Arch] = uigetfile({'*.wav','Archivos de audio grabados (*.wav)';}, ...
            'Escoja el archivo');
    if isequal(Arch,0)
        PFiltrar = figure('Color',[1 1 1], ...
             'MenuBar','none', ...
             'Name','FILTRAR', ...       
             'Position',[695 150 450 200], ...
             'Tag','Fprinc', ...
             'ToolBar','none');
             close (gcf);
    else

        %---------------------------- PANTALLA DE MENU DE FILTRADO ---------------------------       
        %--------------------------------- ventana Filtrar -----------------------------------
        PFiltrar = figure('Color',[1 1 1], ...
            'MenuBar','none', ...
            'Name','FILTRAR', ...
            'NumberTitle','off', ...
            'PaperUnits','points', ...
            'Position',[695 150 450 200], ...
            'Tag','Fprinc', ...
            'ToolBar','none');

        %ejeppal=
        axes('Position',[0 0 1 1]);
        imagen=imread('Sonido2.jpg');
        image(imagen);
        axis off;

        %---------------------------- Boton Aceptar ---------------------------------
        uicontrol('parent',PFiltrar, ...
            'Units','points', ...
            'BackgroundColor',[0.5 0.6 0.8], ...
            'Callback','EnlaceFiltro', ...
            'ListboxTop',0, ...
            'Position',[175 15 70 20], ...
            'String','Aceptar', ...
            'Tag','Baceptar');

        %---------------------------- Boton Cerrar ----------------------------------    
        uicontrol('parent',PFiltrar, ...
            'Units','points', ...
            'BackgroundColor',[0.5 0.6 0.8], ...
            'Callback','close', ...
            'ListboxTop',0, ...
            'Position',[255 15 70 20], ...
            'String','Cerrar', ...
            'Tag','Bcerrar');  

        %-------------------------------------------------------------------------------------
        %Frame Archivo .Wav a filtrar -------------------------------------------------------- 
        uicontrol('parent',PFiltrar,...
            'Style','frame',...
            'Units','points',...
            'BackgroundColor',[0 0 0],...
            'Position',[175 120 150 10],...
            'Tag','Farch');    

        %Texto Archivo .Wav a filtrar --------------------------------------------------------- 
        uicontrol('Parent',PFiltrar,...
            'Style','text', ...
            'Units','points', ...
            'HorizontalAlignment','left', ...
            'BackgroundColor',[0.5 0.6 0.8], ...
            'ListboxTop',0, ...
            'Position',[177 121 150 12], ...
            'String','   Archivo .WAV:', ...
            'Visible','on',...
            'Tag','Tarch');

        %Espacio Archivo .Wav a filtrar ------------------------------------------------------
        uicontrol('parent',PFiltrar, ...
           'Style','edit', ...
           'Units','points', ...
           'HorizontalAlignment','center', ...
           'BackgroundColor',[0.850980392156863 0.925490196078431 1 ], ...
           'ListboxTop',0, ...
           'Position',[245 123 75 10], ...
           'Tag','Earch',...
           'String',Arch);   

        %------------------------------------------------------------------------------------
        %frame Frecuencia Baja de Corte -----------------------------------------------------
        uicontrol('parent',PFiltrar,...
            'Style','frame',...
            'Units','points',...
            'BackgroundColor',[0 0 0],...
            'Position',[175 105 150 10],...
            'Tag','FfrecLow');

        %Texto Frecuencia Baja de Corte -----------------------------------------------------
        uicontrol('Parent',PFiltrar,...
            'Style','text', ...
            'Units','points', ...
            'HorizontalAlignment','left', ...
            'BackgroundColor',[0.5 0.6 0.8], ...
            'ListboxTop',0, ...
            'Position',[177 106 150 12], ...
            'String','   Frecuencia Baja de Corte:', ...
            'Visible','on',...
            'Tag','TfrecLow');

        %Espacio Frecuencia Baja de Corte ---------------------------------------------------- 
        uicontrol('parent',PFiltrar, ...
            'Style','edit', ...
            'Units','points', ...
            'HorizontalAlignment','center', ...
            'BackgroundColor',[0.850980392156863 0.925490196078431 1 ], ...
            'ListboxTop',0, ...
            'Position',[280 108 40 10], ...
            'Tag','EfrecLow',...
            'String','60');  


        %-------------------------------------------------------------------------------------
        %Frame Frecuencia Alta de Corte ----------------------------------------------------
        uicontrol('parent',PFiltrar,...
            'Style','frame',...
            'Units','points',...
            'BackgroundColor',[0 0 0],...
            'Position',[175 90 150 10],...
            'Tag','FfrecHigh');      

        %Texto Frecuencia Alta de Corte ----------------------------------------------------
        uicontrol('Parent',PFiltrar,...
            'Style','text', ...
            'Units','points', ...
            'HorizontalAlignment','left', ...
            'BackgroundColor',[0.5 0.6 0.8], ...
            'ListboxTop',0, ...
            'Position',[177 91 150 12], ...
            'String','   Frecuencia Alta de Corte:', ...
            'Visible','on',...
            'Tag','TfrecHigh');

        %Espacio Frecuencia Alta de Corte ----------------------------------------------------
        uicontrol('parent',PFiltrar, ...
            'Style','edit', ...
            'Units','points', ...
            'HorizontalAlignment','center', ...
            'BackgroundColor',[0.850980392156863 0.925490196078431 1 ], ...
            'ListboxTop',0, ...
            'Position',[280 93 40 10], ...
            'Tag','EfrecHigh',...
            'String','3600');    


        %--------------------------------------------------------------------------------------
        %frame Orden del Filtro ---------------------------------------------------------------
        uicontrol('parent',PFiltrar,...
            'Style','frame',...
            'Units','points',...
            'BackgroundColor',[0 0 0],...
            'Position',[175 75 150 10],...
            'Tag','Forden');

        %Texto Orden del Filtro ----------------------------------------------------------------
        uicontrol('Parent',PFiltrar,...
            'Style','text', ...
            'Units','points', ...
            'HorizontalAlignment','left', ...
            'BackgroundColor',[0.5 0.6 0.8], ...
            'ListboxTop',0, ...
            'Position',[177 76 150 12], ...
            'String','   Orden del Filtro:', ...
            'Visible','on',...
            'Tag','Torden');

        %Espacio Orden del Filtro -------------------------------------------------------------
        uicontrol('parent',PFiltrar, ...
            'Style','edit', ...
            'Units','points', ...
            'HorizontalAlignment','center', ...
            'BackgroundColor',[0.850980392156863 0.925490196078431 1 ], ...
            'ListboxTop',0, ...
            'Position',[280 78 40 10], ...
            'Tag','Eorden',...
            'String','5');

        %--------------------------------------------------------------------------------------
        %frame Tipo de Filtro ----------------------------------------------------------------
        uicontrol('parent',PFiltrar,...
            'Style','frame',...
            'Units','points',...
            'BackgroundColor',[0 0 0],...
            'Position',[175 54 150 16],...
            'Tag','Ftipo');

        %Texto Tipo de Filtro -----------------------------------------------------------------
        uicontrol('parent',PFiltrar,...
            'Style','text', ...
            'Units','points', ...
            'HorizontalAlignment','left', ...
            'BackgroundColor',[0.5 0.6 0.8], ...
            'ListboxTop',1, ...
            'Position',[177 55 150 18], ...
            'String','   Tipo de Filtro:', ...
            'Visible','on',...
            'Tag','Ttipo');

        %Espacio Tipo de Filtro ---------------------------------------------------------------
        tipoFiltro={'FIR' 'IIR'};
        uicontrol('parent',PFiltrar,...
            'Style','popupmenu', ...
            'HorizontalAlignment','left', ...
            'Units','points', ...
            'BackgroundColor',[0.850980392156863 0.925490196078431 1 ], ...
            'Position',[280 62 40 10], ...
            'String',tipoFiltro,...
            'Tag','Btipo');

        %--------------------------------------------------------------------------------------
    end
end        
        