% Produccion.m
% SONIDO 1.0 ®
% Desarrollado Por: Juan Guillermo Valencia Delgado
%                   Sergio Andres Hurtado Ruiz
%                   Felipe Restrepo Naranjo
%                   Jeferson Barrera caceres
% Fecha: Abril de 2009
% Contenido: Información del programa y de sus desarrolladores

function Produccion
   
    Pacercade = figure('Color',[1 1 1], ...
    	'MenuBar','none', ...
        'Name','ACERCA DE...', ...
        'NumberTitle','off', ...
        'Position',[250 150 530 260], ...
        'Tag','Facercade', ...
        'ToolBar','none');

        ejeppal=axes('Position',[0 0 1 1]);
        imagen=imread('ingenieria.jpg');
        image(imagen);
        axis off;
    
    %Boton aceptar-----------------------------------------------------------------------
    Paceptar = uicontrol('parent',Pacercade, ...
        'Units','points', ...
        'BackgroundColor',[0.113725490196078 0.509803921568627 0.945098039215686], ...
        'Callback','close', ...
        'ListboxTop',0, ...
        'Position',[260 50 100 20], ...
        'FontWeight','bold',...
        'String','ACEPTAR', ...
        'Tag','Baceptar', ...
        'UserData','[ ]');
end