% Principal.m
% SONIDO 1.0 ®
% Desarrollado Por: Juan Guillermo Valencia Delgado
%                   Sergio Andres Hurtado Ruiz
%                   Felipe Restrepo Naranjo
%                   Jeferson Barrera caceres
% Fecha: Abril de 2009        
% Contenido:    Menú principal 
%               Se escoge que se desea hacer con el archivo .wav: 
%               Codificar, Decodificar o Filtrar.

function Principal
    
            clear all
    %%---------------------------------- PANTALLA DE INICIO -------------------------------
    if nargin<1
        w=1;
        while w<3            
            %inicio
            figure('Color',[0 0 0], ...
                'MenuBar','none', ...
                'Name','Sinterização V L.0.1', ...
                'NumberTitle','off', ...
                'PaperUnits','points', ...
                'Position',[250 150 559 459], ...
                'Tag','Finicio', ...
                'ToolBar','none');
            
            axes('Position',[0 0 1 1]);
            imagen=imread('Inicio.jpg');
            image(imagen);
            axis off;
            
            %-----------   
            w=w+1;
        end       
        
        %----------------------Sonido de Intro--------------------------------     
%         [dato,fs]=wavread('intro(nomodificar)');
%         p=size(dato,1);
%         t=(1:p)/fs;
%         N=200;
%         n=1:((N-1)/2);
%         w=0.54+0.4*cos(2*pi*n/(N-1));
%         fc1=40/fs;
%         fc2=5000/fs;
%         hd=(sin(2*pi*n*fc2)./(pi*n))-(sin(2*pi*n*fc1)./(pi*n));
%         h=w.*hd;
%         ht=fliplr(h);
%         h0=2*(fc2-fc1);
%         vect=cat(2,ht,h0,h);
%         %------------------Ejecutando reproduccion ------------------------------- 
%         proc=filter(vect,1,dato);
%         wavplay(proc,fs);
        %--------------------------------------------------------------------- 
        
       close;
       d=Retraso;
       if d==1
            close;
       end      
    end

    %--------------------------- VENTANA PRINCIPAL ------------------------------
    %---------------------------- ventana inicial -------------------------------
    Pprinc = figure('Color',[1 1 1], ...
        'MenuBar','none', ...
        'Name','Sinterização V L.0.1', ...
        'NumberTitle','off', ...
        'PaperUnits','points', ...
        'Position',[10 10 994 728], ...
        'Tag','Fprinc', ...
        'ToolBar','none');

    %ejeppal=
    axes('Position',[0 0 1 1]);
    imagen=imread('tela2.jpg');
    image(imagen);
    axis off;
    
    
    
    
    close;
    SinterizacaoVL;

    %---------------------------- Boton Aceptar --------------------------------- 
    %Paceptar = [0.5 0.6 0.8]
    uicontrol('parent',Pprinc, ...
        'Units','points', ...
        'BackgroundColor',[0.5 0.6 0.8], ...
        'Callback','Enlace', ...
        'ListboxTop',0, ...
        'Position',[345 220 90 20], ...
        'String','Aceptar', ...
        'Tag','Baceptar');

    %---------------------------- Boton Grabar -----------------------------------
    %Payuda = 
    uicontrol('parent',Pprinc, ...
        'Units','points', ...
        'BackgroundColor',[0.5 0.6 0.8], ...
        'Callback','tiempo', ...
        'ListboxTop',0, ...
        'Position',[345 105 90 20], ...
        'String','Grabar', ...
        'Tag','Bayuda');

    %---------------------------- Boton Play Archivo------------------------------
    %Pinfo = 
    uicontrol('parent',Pprinc, ...
        'Units','points', ...
        'BackgroundColor',[0.5 0.6 0.8], ...
        'Callback','PlayArchivo', ...
        'ListboxTop',0, ...
        'Position',[345 75 90 20], ...
        'String','Play', ...
        'Tag','Binformacion');

    %---------------------------- Boton Produccuión ------------------------------    
    %Pproduccion = 
    uicontrol('parent',Pprinc, ...
        'Units','points', ...
        'BackgroundColor',[0.5 0.6 0.8], ...
        'Callback','Produccion', ...
        'ListboxTop',0, ...
        'Position',[345 45 90 20], ...
        'String','Producción', ...
        'Tag','Bproduccion');


    %---------------------------- Boton Cerrar ----------------------------------   
    %Pcerrar = 
    uicontrol('parent',Pprinc, ...
        'Units','points', ...
        'BackgroundColor',[0.5 0.6 0.8], ...
        'Callback','close', ...
        'ListboxTop',0, ...
        'Position',[345 15 90 20], ...
        'String','Cerrar', ...
        'Tag','Bcerrar');

    
    %------------------------ Frame tipo de funcion ------------------------------
    %Pframetipofuncion = 
    uicontrol('parent',Pprinc,...
          'Style','frame',...
          'Units','points',...
          'BackgroundColor',[0.2 0.3 0.2],...
          'Position',[342 245 95 55],...
          'Tag','Ftipofuncion');

    %------------------------ Texto tipo de funcion ------------------------------
    %Ptexttipofuncion = 
    uicontrol('Parent',Pprinc,...
        'Style','text', ...
        'Units','points', ...
        'HorizontalAlignment','left', ...
        'BackgroundColor',[0.5 0.6 0.8], ...
        'ListboxTop',1, ...
        'Position',[344 247 91 51], ...
        'String','    QUE DESEA HACER         CON SU ARCHIVO           .WAV?', ...
        'Visible','on',...
        'Tag','Ttipofuncion');

    %------------------------ Boton tipo de funcion -----------------------------
    tipofuncion={'Filtrar' 'Codificar' 'Decodificar'};
    %Ptipofuncion = 
    uicontrol(...
        'Style','popupmenu', ...
        'Units','points', ...
        'BackgroundColor',[0.850980392156863 0.925490196078431 1 ], ...
        'Position',[353 245 75 20], ...
        'String',tipofuncion, ...        
        'Tag','Btipofuncion');%'Callback','enlace',...
end