[arch3dato,padarch3dato] = uigetfile({'*.dat','arquivos de dados (*.dat)';}, ...
            'Carregue o arquivo');
    
    global arquivo3
    arquivo3 = load (arch3dato);
    
            uicontrol('parent',cargador, ...
        'Units','points', ...
        'BackgroundColor',[0.5 0.6 0.8], ...
        'Callback','loadArchivo4', ...
        'ListboxTop',0, ...
        'Position',[345 75 90 20], ...
        'String','Browse', ...
        'Tag','Binformacion');

            uicontrol('Parent',cargador,...
        'Style','text', ...
        'Units','points', ...
        'HorizontalAlignment','left', ...
        'BackgroundColor',[0.5 0.6 0.8], ...
        'ListboxTop',1, ...
        'Position',[240 75 100 18], ...
        'String',arch3dato, ...
        'Visible','on',...
        'Tag','Ttipofuncion');