% Principal.m
% SONIDO 1.0 ®
% Desarrollado Por: Juan Guillermo Valencia Delgado
%                   Sergio Andres Hurtado Ruiz
%                   Felipe Restrepo Naranjo
%                   Jeferson Barrera caceres
% Fecha: Abril de 2009        
% Contenido:    Menú principal 
%               Se escoge que se desea hacer con el archivo .wav: 
%               Codificar, Decodificar o Filtrar.

function Principal
    
            clear all
            global arquivo1
    %%---------------------------------- PANTALLA DE INICIO -------------------------------
    if nargin<1
        w=1;
        while w<3            
            %inicio
            figure('Color',[0 0 0], ...
                'MenuBar','none', ...
                'Name','Sinterização V L.0.1', ...
                'NumberTitle','off', ...
                'PaperUnits','points', ...
                'Position',[250 150 662 544], ...
                'Tag','Finicio', ...
                'ToolBar','none');
            
            axes('Position',[0 0 1 1]);
            imagen=imread('Tela1.bmp');
            image(imagen);
            axis off;
            
            %-----------   
            w=w+1;
        end       
        
       close;
       d=Retraso;
       if d==1
            close;
       end      
    end

    %--------------------------- VENTANA PRINCIPAL ------------------------------
    %---------------------------- ventana inicial -------------------------------
    Pprinc = figure('Color',[1 1 1], ...
        'MenuBar','none', ...
        'Name','Sinterização V L.0.1', ...
        'NumberTitle','off', ...
        'PaperUnits','points', ...
        'Position',[250 150 665 548], ...
        'Tag','Fprinc', ...
        'ToolBar','none');

    %ejeppal=
    axes('Position',[0 0 1 1]);
    imagen=imread('Tela2.bmp');
    image(imagen);
    axis off;
    
    %SinterizacaoVL;

    %---------------------------- Boton Aceptar --------------------------------- 
    %Paceptar = [0.5 0.6 0.8]
    uicontrol('parent',Pprinc, ...
        'Units','points', ...
        'Callback','NuevoProyecto', ...
        'ListboxTop',0, ...
        'Position',[45 120 150 20], ...
        'String','New Project', ...
        'Tag','Baceptar');
    
    uicontrol('parent',Pprinc, ...
        'Units','points', ...
        'Callback','Enlace', ...
        'ListboxTop',0, ...
        'Position',[45 170 150 20], ...
        'String','Load Project', ...
        'Tag','Baceptar');
    
    uicontrol('parent',Pprinc, ...
        'Units','points', ...
        'Callback','Enlace', ...
        'ListboxTop',0, ...
        'Position',[45 70 150 20], ...
        'String','Example Project', ...
        'Tag','Baceptar');
% 
%     %---------------------------- Boton Grabar -----------------------------------
%     %Payuda = 
%     uicontrol('parent',Pprinc, ...
%         'Units','points', ...
%         'BackgroundColor',[0.5 0.6 0.8], ...
%         'Callback','tiempo', ...
%         'ListboxTop',0, ...
%         'Position',[345 105 90 20], ...
%         'String','Grabar', ...
%         'Tag','Bayuda');
% 
%     %---------------------------- Boton Play Archivo------------------------------
%     %Pinfo = 
%     uicontrol('parent',Pprinc, ...
%         'Units','points', ...
%         'BackgroundColor',[0.5 0.6 0.8], ...
%         'Callback','PlayArchivo', ...
%         'ListboxTop',0, ...
%         'Position',[345 75 90 20], ...
%         'String','Play', ...
%         'Tag','Binformacion');
% 
%     %---------------------------- Boton Produccuión ------------------------------    
%     %Pproduccion = 
%     uicontrol('parent',Pprinc, ...
%         'Units','points', ...
%         'BackgroundColor',[0.5 0.6 0.8], ...
%         'Callback','Produccion', ...
%         'ListboxTop',0, ...
%         'Position',[345 45 90 20], ...
%         'String','Producción', ...
%         'Tag','Bproduccion');
% 
% 
%     %---------------------------- Boton Cerrar ----------------------------------   
%     %Pcerrar = 
%     uicontrol('parent',Pprinc, ...
%         'Units','points', ...
%         'BackgroundColor',[0.5 0.6 0.8], ...
%         'Callback','close', ...
%         'ListboxTop',0, ...
%         'Position',[345 15 90 20], ...
%         'String','Cerrar', ...
%         'Tag','Bcerrar');
% 
%     
%     %------------------------ Frame tipo de funcion ------------------------------
%     %Pframetipofuncion = 
%     uicontrol('parent',Pprinc,...
%           'Style','frame',...
%           'Units','points',...
%           'BackgroundColor',[0.2 0.3 0.2],...
%           'Position',[342 245 95 55],...
%           'Tag','Ftipofuncion');
% 
%     %------------------------ Texto tipo de funcion ------------------------------
%     %Ptexttipofuncion = 
%     uicontrol('Parent',Pprinc,...
%         'Style','text', ...
%         'Units','points', ...
%         'HorizontalAlignment','left', ...
%         'BackgroundColor',[0.5 0.6 0.8], ...
%         'ListboxTop',1, ...
%         'Position',[344 247 91 51], ...
%         'String','    QUE DESEA HACER         CON SU ARCHIVO           .WAV?', ...
%         'Visible','on',...
%         'Tag','Ttipofuncion');
% 
%     %------------------------ Boton tipo de funcion -----------------------------
%     tipofuncion={'Filtrar' 'Codificar' 'Decodificar'};
%     %Ptipofuncion = 
%     uicontrol(...
%         'Style','popupmenu', ...
%         'Units','points', ...
%         'BackgroundColor',[0.850980392156863 0.925490196078431 1 ], ...
%         'Position',[353 245 75 20], ...
%         'String',tipofuncion, ...        
%         'Tag','Btipofuncion');%'Callback','enlace',...
end