classdef ViewConstructor
    %Construtor de elementos da interface
    %Garante formatação homogênea no programa
%     
    properties (Constant)
        FontAngle = 'normal'; % | italic | oblique
        FontName = 'MS Sans Serif';     %Font Family
        FontSize = 8;                   %Font size in FontUnits
        FontWeight = 'normal';                %Weiht of the text Characters  {normal} | demi | bold | light 
       
        ForegroundColor = Colors.Preto; %Color of text
        BackgroundColor = Colors.Cinza; %Object Background Color
        BackgroundColor2 = Colors.Branco; %Object Background Color
        ShadowColor = [1.0 1.0 1.0];     %Panel 
        
        Pheigwidth = 200;   % Valor utilizado nas funções do menú móvel de graficos e resultados
        Pheightmin = 20;    % Tamanho minimo do menú móvel de graficos e resultados
        Pheightmax = 100;   % Tamanho Maximo do menú móvel de graficos e resultados
    end
    
    methods (Static)
        
        function rbh = RadioButton (Parent, String, Position, Callback) 
            rbh = uicontrol('Parent', Parent,'Style','radiobutton',...
            'String',String,'Value',0,'Units','normalized',...
            'Position',Position,'Callback',Callback);
        end        
        function text = Text (Parent, Position, Text)
            text = uicontrol('Parent',Parent,'Style','text',...
            'String',Text, 'Units', 'normalized',...
            'Position',Position,'FontWeight',ViewConstructor.FontWeight,...
            'FontSize',ViewConstructor.FontSize,...
            'BackgroundColor',ViewConstructor.BackgroundColor,...
            'HorizontalAlignment','center',...
            'ForegroundColor', ViewConstructor.ForegroundColor); %ForeColor [1.0 1.0 1.0] BackColor [0.392 0.475 0.635]
 
        end           
        function popup = Popupmenu (Parent, Position, String,Callback)
            popup = uicontrol('Parent', Parent,'Style','popupmenu',...
            'String',String, 'Units', 'normalized',...
            'Value',1,'Position',Position,...
            'BackgroundColor',ViewConstructor.BackgroundColor2,...
            'FontSize',ViewConstructor.FontSize,'Callback',Callback);
        end        
        function panel = Panel (Parent, Title)
            panel = uipanel('Parent',Parent,...
            'TitlePosition','lefttop',...
            'Title',Title,...
            'Units','normalized',...
            'BorderType','etchedin',...
            'FontWeight','demi',...
            'FontSize',ViewConstructor.FontSize,...
            'FontName','MS Sans Serif',...
            'FontUnits','points',...
            'BackgroundColor',Colors.Cinza,...
            'ShadowColor', [0 0 0]);
        end
        function fundo = Fundo (Parent)
            fundo = uipanel('Parent',Parent,...
            'TitlePosition','lefttop',...
            'Units','normalized',...
            'BorderType','none',...
            'BackgroundColor',Colors.Cinza);
        end
        function listbox = Listbox (Parent, Position, Var, Callback)
            listbox = uicontrol('Parent',Parent,'Style','listbox',...
            'String',Var, 'Units','normalized',...
            'Value',1,'Position',Position,...
            'BackgroundColor', [1.0 1.0 1.0], 'Callback', Callback);
        end
        function textEdit = EditText (Parent, Position, Callback)
            textEdit = uicontrol('Parent', Parent,'Style','edit',...
            'Max',1,'Min',0,...
            'Units', 'normalized',...
            'Position',Position,...
            'BackgroundColor',ViewConstructor.BackgroundColor2,...
            'Callback',Callback);
        end
        function cbh = Checkbox (Parent, String, Position, Value, Callback)
            cbh = uicontrol('Parent', Parent,'Style','checkbox',...
            'String',String,...
            'Value',Value,'Units', 'normalized','Position',Position,...
            'BackgroundColor',ViewConstructor.BackgroundColor,...
            'Callback',Callback);
        end
        function button = Button (Parent, String, Position, Callback)
            button= uicontrol('Parent',Parent,'Style','pushbutton',...
            'String',String,'Units','normalized','Position',Position,...
            'Callback',Callback,'BackgroundColor', Colors.Cinza,...
            'FontSize',ViewConstructor.FontSize,...
            'FontWeight',ViewConstructor.FontWeight);   

        end
        function table = Table (Parent,ColumnName,ColumnFormat,ColumnEditable,ColumnWidth,Position,CellEditCallback,CellSelectionCallback)
            table = uitable('Parent',Parent,'ColumnName',ColumnName,'ColumnFormat',...
                ColumnFormat,'ColumnEditable',ColumnEditable,'RowName',[],'ColumnWidth',ColumnWidth,...
                'Units', 'normalized', 'Position', Position,'RowStriping','on','BackgroundColor', [Colors.Cinzaescuro; Colors.Cinza],...
                'CellEditCallback',CellEditCallback,...
                'CellSelectionCallback',CellSelectionCallback,...
                'SelectionHighlight','off',...
                'FontSize',ViewConstructor.FontSize,'ForegroundColor',ViewConstructor.ForegroundColor);
        end
        function slider = Slider (Parent,Min,Max,Value,Position,Callback)
            slider = uicontrol('Parent',Parent,'Style','slider',...
            'Min',Min,'Max',Max,'Value',Value,...
             'Units', 'normalized','Position', Position,...
            'Callback', Callback);
        end

    end
      
    
end

